---
blank_issues_enabled: true
contact_links:
  - name: ğŸ“ Ansible Code of Conduct
    url: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_template_chooser
    about: The cisco.ios collection follows the Ansible Code of Conduct; â¤ Be nice to other members of the community. â˜® Behave.
