---
name: Code Coverage New
on: # yamllint disable-line rule:truthy
  pull_request:

jobs:
  codecoverage:
    name: Code Coverage | Python 3.12
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install ansible-core pytest pytest-cov pytest-ansible-units pytest-forked pytest-xdist

      - name: Run unit tests with coverage
        run: |
          pytest tests/unit -v --cov=./ --cov-report=xml

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Save PR number
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: Upload PR number artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number.txt
