---
name: "Collection Tests ðŸ§ª"

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.event_name }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sonar:
    name: SonarCloud
    if: github.event_name == 'push' || github.event_name == 'pull_request_target'
    uses: ansible/ansible-content-actions/.github/workflows/sonarcloud.yaml@main
    with:
      python_version: "3.12"
      galaxy_dependencies: |
        git+https://github.com/ansible-collections/ansible.utils.git
        git+https://github.com/ansible-collections/ansible.netcommon.git
    secrets:
      SONAR_TOKEN: ${{ secrets.ANSIBLE_COLLECTIONS_ORG_SONAR_TOKEN_CICD_BOT }}

  changelog:
    uses: ansible/ansible-content-actions/.github/workflows/changelog.yaml@main
    if: github.event_name == 'pull_request'

  build-import:
    uses: ansible/ansible-content-actions/.github/workflows/build_import.yaml@main
    if: github.event_name != 'push' && github.event_name != 'pull_request_target'

  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    if: github.event_name != 'push' && github.event_name != 'pull_request_target'

  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@main
    if: github.event_name != 'push' && github.event_name != 'pull_request_target'

  unit-galaxy:
    uses: ansible/ansible-content-actions/.github/workflows/unit.yaml@main
    if: github.event_name != 'push' && github.event_name != 'pull_request_target'

  unit-source:
    uses: ansible-network/github_actions/.github/workflows/unit_source.yml@main
    if: github.event_name != 'push' && github.event_name != 'pull_request_target'
    with:
      collection_pre_install: >-
        git+https://github.com/ansible-collections/ansible.utils.git
        git+https://github.com/ansible-collections/ansible.netcommon.git

  all_green:
    if: ${{ always() }}
    needs:
      - changelog
      - build-import
      - sanity
      - unit-galaxy
      - ansible-lint
      - sonar
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert 'failure' not in
          set([
          '${{ needs.changelog.result }}',
          '${{ needs.build-import.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.unit-galaxy.result }}',
          '${{ needs.ansible-lint.result }}',
          '${{ needs.unit-source.result }}',
          '${{ needs.sonar.result }}'
          ])"
